// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: event.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace KDGame.PB {

  /// <summary>Holder for reflection information generated from event.proto</summary>
  public static partial class EventReflection {

    #region Descriptor
    /// <summary>File descriptor for event.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EventReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgtldmVudC5wcm90bxIJS0RHYW1lLlBCKi0KCkxvZ2ljRXZlbnQSCwoHTm90",
            "aGluZxAAEhIKDkxhdW5jaEJ0bkNsaWNrEAFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::KDGame.PB.LogicEvent), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum LogicEvent {
    [pbr::OriginalName("Nothing")] Nothing = 0,
    [pbr::OriginalName("LaunchBtnClick")] LaunchBtnClick = 1,
  }

  #endregion

}

#endregion Designer generated code
