// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: main.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace KDGame.PB {

  /// <summary>Holder for reflection information generated from main.proto</summary>
  public static partial class MainReflection {

    #region Descriptor
    /// <summary>File descriptor for main.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MainReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgptYWluLnByb3RvEglLREdhbWUuUEIiVQoLUnVudGltZUluZm8SHwoDZW52",
            "GAEgASgOMhIuS0RHYW1lLlBCLkVudk5hbWUSJQoIcGxhdGZvcm0YAiABKA4y",
            "Ey5LREdhbWUuUEIuUGxhdGZvcm0qIQoHRW52TmFtZRIJCgVERUJVRxAAEgsK",
            "B1JFTEVBU0UQASotCghQbGF0Zm9ybRILCgdVTktOT1dOEAASCwoHQU5EUk9J",
            "RBABEgcKA0lPUxACYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::KDGame.PB.EnvName), typeof(global::KDGame.PB.Platform), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::KDGame.PB.RuntimeInfo), global::KDGame.PB.RuntimeInfo.Parser, new[]{ "Env", "Platform" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum EnvName {
    [pbr::OriginalName("DEBUG")] Debug = 0,
    [pbr::OriginalName("RELEASE")] Release = 1,
  }

  public enum Platform {
    [pbr::OriginalName("UNKNOWN")] Unknown = 0,
    [pbr::OriginalName("ANDROID")] Android = 1,
    [pbr::OriginalName("IOS")] Ios = 2,
  }

  #endregion

  #region Messages
  public sealed partial class RuntimeInfo : pb::IMessage<RuntimeInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RuntimeInfo> _parser = new pb::MessageParser<RuntimeInfo>(() => new RuntimeInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RuntimeInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::KDGame.PB.MainReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RuntimeInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RuntimeInfo(RuntimeInfo other) : this() {
      env_ = other.env_;
      platform_ = other.platform_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RuntimeInfo Clone() {
      return new RuntimeInfo(this);
    }

    /// <summary>Field number for the "env" field.</summary>
    public const int EnvFieldNumber = 1;
    private global::KDGame.PB.EnvName env_ = global::KDGame.PB.EnvName.Debug;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::KDGame.PB.EnvName Env {
      get { return env_; }
      set {
        env_ = value;
      }
    }

    /// <summary>Field number for the "platform" field.</summary>
    public const int PlatformFieldNumber = 2;
    private global::KDGame.PB.Platform platform_ = global::KDGame.PB.Platform.Unknown;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::KDGame.PB.Platform Platform {
      get { return platform_; }
      set {
        platform_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RuntimeInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RuntimeInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Env != other.Env) return false;
      if (Platform != other.Platform) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Env != global::KDGame.PB.EnvName.Debug) hash ^= Env.GetHashCode();
      if (Platform != global::KDGame.PB.Platform.Unknown) hash ^= Platform.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Env != global::KDGame.PB.EnvName.Debug) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Env);
      }
      if (Platform != global::KDGame.PB.Platform.Unknown) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Platform);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Env != global::KDGame.PB.EnvName.Debug) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Env);
      }
      if (Platform != global::KDGame.PB.Platform.Unknown) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Platform);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Env != global::KDGame.PB.EnvName.Debug) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Env);
      }
      if (Platform != global::KDGame.PB.Platform.Unknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Platform);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RuntimeInfo other) {
      if (other == null) {
        return;
      }
      if (other.Env != global::KDGame.PB.EnvName.Debug) {
        Env = other.Env;
      }
      if (other.Platform != global::KDGame.PB.Platform.Unknown) {
        Platform = other.Platform;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Env = (global::KDGame.PB.EnvName) input.ReadEnum();
            break;
          }
          case 16: {
            Platform = (global::KDGame.PB.Platform) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Env = (global::KDGame.PB.EnvName) input.ReadEnum();
            break;
          }
          case 16: {
            Platform = (global::KDGame.PB.Platform) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
